### ISSUE TITLE
Any updates for v4.3.x?

### ISSUE THREAD

**Issue by directentis1** [pjy612/fiddler-everywhere-enhance-backup#1]
I wonder if there is a new update for v4.3.x or does the old way of your instructions still work?

 Thank you for your valuable time and effort for this job, indeed for a Software Safety student, such tools are indispensable, although it's quite expensive to buy or rent :/

**Comment by pjy612** [comment]
You can try the 4.2.x patch, but there is no guarantee that all the features of 4.3 will work.

**Comment by directentis1** [comment]
I've tried, but unfortunately, it doesn't works :/

**Comment by pjy612** [comment]
Updated, but not fully supported v4.3.x
branch local

![image](https://github.com/pjy612/fiddler-everywhere-enhance-backup/assets/4072526/3e813ade-46b4-48a0-9953-6e1b232f4326)

**Comment by directentis1** [comment]
@pjy612 Thanks for your hard work.
But does that mean I don't need edit Fiddler.WebUi.dll and main.xxxx.js anymore?
I spent a whole day editing them with dnSpy (https://github.com/dnSpyEx/dnSpy) with no success, lol
Btw, can you give me a tutorial for recent versions?

**Comment by pjy612** [comment]
> @pjy612 Thanks for your hard work. But does that mean I don't need edit Fiddler.WebUi.dll and main.xxxx.js anymore? I spent a whole day editing them with dnSpy (https://github.com/dnSpyEx/dnSpy) with no success, lol Btw, can you give me a tutorial for recent versions?

The latest version does not have any tutorials. 
Because it adds protection, it can't be solved perfectly at the moment. 
recommend using version v4.0.1 and the patch. 
That is the last version that can be customized basically at will.

https://github.com/pjy612/fiddler-everywhere-enhance/issues/4

**Comment by directentis1** [comment]
I saw something like that in your code...
 although I don't understand all of them, but I guess that's the function Telerik added to prevent decompilation of their app?
I'm just curious, cause I don't have any experiences with dotnet 😓 (I'm mainly use Linux for study and work)

![image](https://github.com/pjy612/fiddler-everywhere-enhance-backup/assets/128832114/e5db4b2d-218d-4e47-975c-686eb9e1a31b)
